### ISSUE TITLE
Switch test framework

### ISSUE THREAD

**Issue by edgarriba** [tiny-dnn/tiny-dnn#242]
I open this ticket to discuss about switching the test framework. My idea is the following:
- Migrate to [GTest](https://cmake.org/cmake/help/v3.0/module/FindGTest.html). Force user to install it and use command `findPackage(GTest)`.
- Include tests in CMake format using command  `add_test`.

**Comment by patrikhuber** [comment]
When I last checked 1 year ago, it was recommended by GTest authors to
include GTest into the project and not use and external, separately built
one. I believe one reason was so that compile flags match.

Have you looked at Catch? It's header-only and quite appealing.

**Comment by edgarriba** [comment]
@patrikhuber whatever option that's easy to integrate with CMake is okay.
However, Gtest you can easily get it via `apt-get install libgtest-dev` if I'm not wrong.

**Comment by patrikhuber** [comment]
I think the reason is in their FAQ (and it was a pretty good one), if you
can't find it I'll check tomorrow. I think I went with add_subdirectory
(you can copy from my superviseddescent project on GitHub) but better first
check if this info is still up to date :)

**Comment by edgarriba** [comment]
If we agree to include third-party libraries at least for testing, your solution looks good to me.

**Comment by patrikhuber** [comment]
Found it, it's in the [GTest FAQ](https://github.com/google/googletest/blob/master/googletest/docs/FAQ.md#why-is-it-not-recommended-to-install-a-pre-compiled-copy-of-google-test-for-example-into-usrlocal) :-) Apparently it's because of ODR and `#ifdef`'s in GTest, but I don't fully understand without thinking more about it.

Anyway I recommend giving [Catch](https://github.com/philsquared/Catch) a thought, I think if I were to redo my Unit tests I might switch (not that setup/integration of GTest is a huge hassle, but there can be some issues and a header-only file is certainly easier).

**Comment by nyanp** [comment]
I think it's no problem to include third-party libraries under specific (e.g. ```thrid_party```) directory for testing, if its license has no problem to include. Since picotest has compatibility with gtest and I don't think gtest has critical problems, I vote for gtest.
I like Catch as a header-only-believer, and it's a very good alternative if we have problem with gtest :)
