### ISSUE TITLE
MSVC2015 and MSVC2013 compilers: same code produces different results

### ISSUE THREAD

**Issue by pi-null-mezon** [tiny-dnn/tiny-dnn#284]
Hi. I am trying to implement tiny-dnn for the image segmentation and have found strange behavior of my program when compile with different compilers. Here the example. The network has been learned to segment sky on images.

Control sample: 

![1](https://cloud.githubusercontent.com/assets/5991537/17801680/29ca1442-65f4-11e6-87e0-5dfc847f6360.jpg)

Segmentation by program that has been compiled by MSVC2013 (both x86 and x64 are equal):

![image](https://cloud.githubusercontent.com/assets/5991537/17801709/5ca41278-65f4-11e6-9ecf-a9e0d5e06525.png)

Segmentation by program that has been compiled by MSVC2015 (both x86 and x64 are equal):

![image](https://cloud.githubusercontent.com/assets/5991537/17801729/8506e7f4-65f4-11e6-9572-eabbcfd41653.png)

So, why this could happen? Maybe weights initialization works different?

**Comment by nyanp** [comment]
@pi-null-mezon 
Possibly so. tiny-dnn use ```std::uniform_real_distribution``` for weights initialization, and the algorithm for producing values for ```double``` types differs between msvc2015 and msvc2013.

from C++11 standard, 26.5.8.1/p3
> The algorithms for producing each of the specified distributions are implementation-defined.

If it is caused by algorithm difference of distributions, changing seed value via  ```tiny_dnn::set_random_seed(unsigned int)``` will improve your result in msvc2015. Thanks!

**Comment by pi-null-mezon** [comment]
Yes, `tiny_dnn::set_random_seed(unsigned int)` works.
