### ISSUE TITLE
MNIST test.cpp file not compiling

### ISSUE THREAD

**Issue by skazmi1** [tiny-dnn/tiny-dnn#406]
Tried compiling the test.cpp file from tiny_dnn / examples / mnist / test.cpp. It gives a "Debug Assertation Failed" error with Expression: vector iterator not dereferencable. Ignoring that yields Expression: "Standard C++ Libraries Out of Range" &&0

**Comment by beru** [comment]
What compiler did you use?
Please provide information to reproduce the issue.

**Comment by skazmi1** [comment]
Visual C++ 14.0 compiler that comes with VS 2015. Sorry im new to this :D I used Cmake to build the project and since it didnt contain the test.cpp file so I added a new file to the project and built that which gave the error

**Comment by beru** [comment]
@skazmi1 In `CMakeLists.txt` file, please set `BUILD_EXAMPLES` option to `ON` with your text editor.
To make Visual Studio projects, I use below cmake command on command prompt.
`cmake -g "Visual Studio 14 2015 Win64"`

**Comment by skazmi1** [comment]
I did that and now the test.cpp comes with the project. However, compiling it yields "Unhandled exception at 0x7729C54F in example_mnist_test.exe: Microsoft C++ exception: tiny_dnn::nn_error at memory location 0x003CF830.". This error is thrown in a couple of tiny_dnn's files and in xmemory0 visual studio file.

**Comment by beru** [comment]
Firstly, you have to train neural network with `example_mnist_train` project. Build the project and run the program from Visual Studio with command line argument `../data`. After the training is finished, `LeNet-model` file will be created in `examples` folder (if you run the program from Visual Studio). As a side note, default working directory of VC++ projects is `$(ProjectDir)` that means working directory of the program is `examples` since `example_mnist_train.vcxproj` file is in the folder.

After that, build `example_mnist_test` project and run the program from Visual Studio with command line argument `4.bmp`. The file `4.bmp` can be downloaded from [here](https://github.com/tiny-dnn/tiny-dnn/wiki/4.bmp). So place the downloaded file in `examples` folder before you run the program from Visual Studio.

**Comment by skazmi1** [comment]
I ran the train.cpp file with ../data as a parameter. However, it gives the same error "Unhandled exception at 0x7729C54F in example_mnist_train.exe: Microsoft C++ exception: std::bad_alloc at memory location 0x002AF464."

**Comment by skazmi1** [comment]
I just replaced the ../data with the data folder path in the tinydnn file and its now working with a progress bar. It has taken about half an hour and still continuing but i hope this is normal. Thanks a lot for helping me out :). Ill let you know if the next steps have any issue

**Comment by skazmi1** [comment]
Its been about an hour. Is this normal considering it only took 13 minutes for the training by the devs in the readme file

**Comment by beru** [comment]
Did you run `Release` build of `example_mnist_train` project?

If you used `Debug` build, please select menu item `Build`, then select a submenu item `Configuration Manager...`. The Configuration Manager dialog will appear so change `Active solution configuration:` to `Release` and push `Close` button and built the program again.

**Comment by skazmi1** [comment]
I did that. Its working perfectly fine now

**Comment by bhack** [comment]
This kind of pure support issues need to be forwarded to stackoverflow with tiny-dnn tag cause when issue is closed knowledge will be lost.
