### ISSUE TITLE
New interface for creating Layers

### ISSUE THREAD

**Issue by Polyacene** [tiny-dnn/tiny-dnn#671]
Recently I started to play with tiny-dnn and I do enjoy the simplicity in using it.
Yesterday I performed an update and realized that the interface for creating layers has changed.

In my test application I used to create layers via
```cpp
        network<sequential> nn;
        nn  << fully_connected_layer<tan_h>(1, NumHidden)
              << fully_connected_layer<tan_h>(NumHidden, NumHidden)
              << fully_connected_layer<identity>(NumHidden, 1);
```
according to the documentation I found I changed it to

```cpp
	network<sequential> nn;
  	nn 	<< fully_connected_layer(1, NumHidden) <<  tiny_dnn::activation::tanh()
 		<< fully_connected_layer(NumHidden, NumHidden)<< tiny_dnn::activation::tanh()
 		<< fully_connected_layer(NumHidden, 1) ;
```
which happily compiles. Note, I can't just use tanh() as the compiler issues an error on a conflict with tanh(double).

However, I'm now confused concerning the type of network I'm actually creating.

```cpp
	for (int i = 0; i < nn.depth(); i++) 
	{
		std::cout << "#layer :" << i << "\n";
		std::cout << "#\ttype  :" << nn[i]->layer_type() << "\n";
		std::cout << "#\tinput :" << nn[i]->in_data_size() << "(" << nn[i]->in_data_shape() << ")\n";
		std::cout << "#\toutput:" << nn[i]->out_data_size() << "(" << nn[i]->out_data_shape() << ")\n" << std::endl;
	}
```

reports me 5 layer:

```
#layer :0
#       type  :fully-connected
#       input :1([[1x1x1]])
#       output:20([[20x1x1]])

#layer :1
#       type  :tanh-activation
#       input :20([[20x1x1]])
#       output:20([[20x1x1]])

#layer :2
#       type  :fully-connected
#       input :20([[20x1x1]])
#       output:20([[20x1x1]])

#layer :3
#       type  :tanh-activation
#       input :20([[20x1x1]])
#       output:20([[20x1x1]])

#layer :4
#       type  :fully-connected
#       input :20([[20x1x1]])
#       output:1([[1x1x1]])
```

I also wonder whether the linear (identity) activation is gone.

**Comment by Polyacene** [comment]
Here I've attached a graph of the above network using ` graph_visualizer viz(nn, "graph"); ` .
![graph](https://cloud.githubusercontent.com/assets/27062506/25474877/136661d6-2b35-11e7-9981-502a8677a601.gif) 
Does tanh-activation mean, that it is only the activation type or is it a separate layer wit a 20x20 matrix?
If it's only the activation, should I also place one before the first layer if I want a tanh activation of the input?

**Comment by karandesai-96** [comment]
Hi, @Polyacene, a long reply follows:

> Recently I started to play with tiny-dnn and I do enjoy the simplicity in using it.

Nice to hear that, I am a recent contributor and I had the same reason to join :smile: 

> Note, I can't just use tanh() as the compiler issues an error on a conflict with tanh(double).

One is `std::tanh` and another is `tiny_dnn::activation::tanh`. if you intend to use both, you might want to do something like:

```c++
using namespace std;
// using namespace tiny_dnn::activation;    !!! this causes conflicts
using namespace A = tiny_dnn::activation;

nn << fc(32, 10) << A::tanh() ...
```
or conversely the same for `std::tanh`, your choice,

> Yesterday I performed an update and realized that the interface for creating layers has changed.  

`layer<activation>` combinations were a lot in tiny-dnn and we use `cereal` library for serialization of network architecture to a JSON file. Due to too many `layer<activation>` combinations, we used to define a bunch of macros. That resulted in a severe compilation time. Another reason was to simplify building python bindings in the future.

> reports me 5 layer:  

Activations are now implemented as layers in tiny-dnn new API. Hence there are five layers reported, which is perfectly fine. Initially, layers with activations used to have two outputs - actual data (which was obtained after applying activation), and auxiliary data, which was before applying activation. Hence that is now separated into a separate layer and hence memory consumed is roughly the same. 

> I also wonder whether the linear (identity) activation is gone.

We do not need identity activation anymore as layers do not have any activation so everything is identity :smile: 

> Does tanh-activation mean, that it is only the activation type or is it a separate layer wit a 20x20 matrix?

Separate layer. The old graph looked like this:
![image](https://cloud.githubusercontent.com/assets/10494087/25495272/371d3518-2b9a-11e7-8188-bd757a79678f.png)
See how `aux` is gone now ? That's transformed into a new layer.

> If it's only the activation, should I also place one before the first layer if I want a tanh activation of the input?

If you wish to take tanh of input, you will have to add a tanh layer in the beginning. Yes.

Further queries ?

**Comment by Polyacene** [comment]
Dear @karandesai-96 , thanks for your clarifying answer.
Just to be sure.

> We do not need identity activation anymore as layers do not have any activation so everything is identity

I thought identity actually means a linear activation performing a scaling the output. As far as I understand your explanation, there's no scaling involved in the output of a fully-connected layer. Can this be achieved?

Out of curiosity, could I now use a tanh ( tanh() ) activation by inserting
`<< tiny_dnn::activation::tanh() << tiny_dnn::activation::tanh() ; ` ?

**Comment by karandesai-96** [comment]
> I thought identity actually means a linear activation performing a scaling the output. As far as I understand your explanation, there's no scaling involved in the output of a fully-connected layer. Can this be achieved?

Identity was simply following y = x line. Have a look at [linear_layer.h](https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/layers/linear_layer.h#L17). I think it fulfills your needs.

Alternatively, if you wish to play more, you can write a custom activation. A detailed step by step guide is outlined [here](https://github.com/tiny-dnn/tiny-dnn/blob/master/docs/developer_guides/Writing-Custom-Activations.md).

> Out of curiosity, could I now use a tanh ( tanh() ) activation

Yes, the line of code you wrote will do the thing for you :smile:

**Comment by Polyacene** [comment]
@karandesai-96 I looked into linear_layer.h and what I actually would like to use is `layers::linear() << tiny_dnn::activation::tanh()` .
To start I tried to fit a linear function with `layers::linear`. If I initialize it with the solution it works fine.
However, it looks that the scaling and and shifting is not subject to the optimization. Is this intentional or am I'm missing something?

**Comment by karandesai-96** [comment]
Right, scaling and shifting are not learnable parameters yet. So this layer is basically like existing activation layers. Thanks for the idea, now we can think of enhancing it!

**Comment by Polyacene** [comment]
@karandesai-96 I think for projects trying to fit functions instead of classifying categories this could be really useful.
