### ISSUE TITLE
similarity search

### ISSUE THREAD

**Issue by jojo05** [tiny-dnn/tiny-dnn#798]
Thank you for this excellent library !

I have 3 questions/comments:

1) I saw on another issue that you plan to offer the ability to import other models (like imagenet models?) by the end of summer. Can you share more info?

2) What existing model do you recommend for image similarity search, i.e. get an image vector and compare via cosine similarity with other images?

3) What is the query time comparison with other libraries using GPUs? 

Thanks

**Comment by jojo05** [comment]
Related to point 2, this was published today
https://medium.com/@deepmike/hacking-on-semantic-image-search-f8e4ca55278b

**Comment by edgarriba** [comment]
in this case they don't mention how similarity in enforced, I guess they just trained a resnet and use the features vector to query stuff. To train networks like this it's better to use another framework like Caffe or Pytorch, mainly because we don't still support GPU. Once you have your model trained, you can import it to tiny-dnn and perform just inference.

We plan to give support to import state of the art models by the end of the summer. @karandesai-96 working on that. The idea is to be able to import parameters independently the framework used for training, you will just need the file with data per layer and its definition, let's say number of neurons and kernel size in the case of convs.

**Comment by jojo05** [comment]
The similarity search case I have in mind (heard in a video presentation by some googler) would not require training:
1) get the output vector from a imagenet model
2) compare the images via these vectors
The first great use for tiny-dnn is to be able to use a SOTA model for inference

**Comment by edgarriba** [comment]
the best you can do by now is import a caffemodel
https://github.com/BVLC/caffe/tree/master/models/bvlc_alexnet

**Comment by jojo05** [comment]
Ok, will try that, thanks

**Comment by edgarriba** [comment]
@jojo05 cool. Closing this.
