### ISSUE TITLE
Master branch fails to build

### ISSUE THREAD

**Issue by Ravenwater** [tiny-dnn/tiny-dnn#971]
Getting 15 compilation failures in master branch build:
```
115>------ Rebuild All started: Project: ALL_BUILD, Configuration: Release x64 ------
115>Building Custom Rule C:/Users/tomtz/Documents/dev/clones/tiny-dnn/CMakeLists.txt
115>CMake does not need to re-run because C:/Users/tomtz/Documents/dev/clones/tiny-dnn/build/CMakeFiles/generate.stamp is up-to-date.
========== Rebuild All: 100 succeeded, 15 failed, 0 skipped ==========
```

Related to this error:

```
42>sinus_fit.cpp
42>c:\users\tomtz\documents\dev\clones\tiny-dnn\tiny_dnn\xtensor\xcontainer.hpp(641): error C3203: 'layout_iterator': unspecialized alias template can't be used as a template argument for template parameter '_Ty2', expected a real type
42>c:\users\tomtz\documents\dev\clones\tiny-dnn\tiny_dnn\xtensor\xcontainer.hpp(650): error C3203: 'layout_iterator': unspecialized alias template can't be used as a template argument for template parameter '_Ty2', expected a real type
42>c:\users\tomtz\documents\dev\clones\tiny-dnn\tiny_dnn\xtensor\xcontainer.hpp(659): error C3203: 'const_layout_iterator': unspecialized alias template can't be used as a template argument for template parameter '_Ty2', expected a real type
42>c:\users\tomtz\documents\dev\clones\tiny-dnn\tiny_dnn\xtensor\xcontainer.hpp(665): error C3203: 'const_layout_iterator': unspecialized alias template can't be used as a template argument for template parameter '_Ty2', expected a real type
42>c:\users\tomtz\documents\dev\clones\tiny-dnn\tiny_dnn\xtensor\xcontainer.hpp(671): error C3203: 'const_layout_iterator': unspecialized alias template can't be used as a template argument for template parameter '_Ty2', expected a real type
42>c:\users\tomtz\documents\dev\clones\tiny-dnn\tiny_dnn\xtensor\xcontainer.hpp(680): error C3203: 'const_layout_iterator': unspecialized alias template can't be used as a template argument for template parameter '_Ty2', expected a real type
42>c:\users\tomtz\documents\dev\clones\tiny-dnn\tiny_dnn\xtensor\xcontainer.hpp(689): error C3203: 'reverse_layout_iterator': unspecialized alias template can't be used as a template argument for template parameter '_Ty2', expected a real type
42>c:\users\tomtz\documents\dev\clones\tiny-dnn\tiny_dnn\xtensor\xcontainer.hpp(698): error C3203: 'reverse_layout_iterator': unspecialized alias template can't be used as a template argument for template parameter '_Ty2', expected a real type
42>c:\users\tomtz\documents\dev\clones\tiny-dnn\tiny_dnn\xtensor\xcontainer.hpp(708): error C3203: 'const_reverse_layout_iterator': unspecialized alias template can't be used as a template argument for template parameter '_Ty2', expected a real type
42>c:\users\tomtz\documents\dev\clones\tiny-dnn\tiny_dnn\xtensor\xcontainer.hpp(715): error C3203: 'const_reverse_layout_iterator': unspecialized alias template can't be used as a template argument for template parameter '_Ty2', expected a real type
42>c:\users\tomtz\documents\dev\clones\tiny-dnn\tiny_dnn\xtensor\xcontainer.hpp(722): error C3203: 'const_reverse_layout_iterator': unspecialized alias template can't be used as a template argument for template parameter '_Ty2', expected a real type
42>c:\users\tomtz\documents\dev\clones\tiny-dnn\tiny_dnn\xtensor\xcontainer.hpp(732): error C3203: 'const_reverse_layout_iterator': unspecialized alias template can't be used as a template argument for template parameter '_Ty2', expected a real type
```

any pointers to what is causing this?

**Comment by beru** [comment]
@Ravenwater Judging from the error message, https://github.com/tiny-dnn/tiny-dnn/issues/949#issuecomment-391408664 should solve the problem.

**Comment by Ravenwater** [comment]
Indeed, I did find that comment when googling the error message, and pulled the gist into my fork. Disappointing that this didn't make it into master, as I presume that many of the 1145 forks out there had to do that.

**Comment by beru** [comment]
In the past, I sent PR #947 to remove xtensor library from tiny-dnn to solve the compilation errors but other maintainers hesitated to the change so I gave up the PR. 

xtensor integration has been abandoned and its routines aren't acutually used during computation (since it's not working). I don't think keeping broken or unfinished code within master branch is meaninful.

**Comment by Ravenwater** [comment]
@beru agreed. It appears that the project has a good community with lots of interest, but has accrued a lot of tech debt that has messed up the core. We would first need to clean that up. This would require a developer, or set of developers, that have a complete understanding of the architecture, why the code was organized that way, and where the code needed to go. WRT to xtensor, it would be good to understand why the integration failed: was it something in the architecture of tiny-dnn, or in the public API of xtensor.

**Comment by beru** [comment]
> WRT to xtensor, it would be good to understand why the integration failed: was it something in the architecture of tiny-dnn, or in the public API of xtensor.

I suspect it must be due to lack of efforts and abilities. But to put it mildly, the task might be harder than predicted and as you mentioned, a lot of technical debts probablly hindered the process.

---

https://github.com/tiny-dnn/tiny-dnn/blob/a8de26ad40d955908c5ec4fc946c3c67dd381c6c/tiny_dnn/util/util.h#L66

```cpp
typedef std::vector<float_t, aligned_allocator<float_t, 64>> vec_t;
typedef std::vector<vec_t> tensor_t;
```

This is what tiny-dnn uses as tensor structure. Organization developers have wanted to replace this with more feature rich ndarray class. Initially, developers tried to make in-house tensor class and later, they decided to use xtensor library to achieve the goal. 

I can continue on writing about this topic with a lot of nonsenses but let me abstain from doing so. :speak_no_evil:

**Comment by edgarriba** [comment]
@Ravenwater since we don't touch that much the high level API I think the rest can happen internally. Actually that was one of the goals of the tensor integration task and probably the reason of this forked backends system in order to make it all incrementally. But it all depends on the final goals and how much we want to expose to users. As I understood one of your main concerns is about training right ? Targeting known architectures could be one thing instead of having one more DL framework to rule them all. On the other hand, as you said before we don't have an army of paid engineers to develop and maintain this project. So we have to be realistic on what and we can do.

**Comment by beru** [comment]
Applied a workaround for Visual Studio 2017 >=.
https://github.com/tiny-dnn/tiny-dnn/commit/d0d35ca2f4e75b3f647787e19ee7f31d0784b398#diff-4affbaaacf4e0188e9d590b10b028d0e

**Comment by beru** [comment]
The patch has landed on master branch so I'm closing this issue.
